# This configuration was generated by Terraform

## Node
# datacenter = "$${datacenter}"
# node_name  = "$${node_name}"
# domain     = "$${domain}"

## Addresses
bind_addr          = "$${NODE_IP}"
advertise_addr     = "$${NODE_IP}"
advertise_addr_wan = "$${NODE_IP}"
# client_addr        = "127.0.0.1"
client_addr        = "$${NODE_IP}"

addresses = {
  dns   = "127.0.0.1"
  # http  = "127.0.0.1"
  http = "$${NODE_IP}"
  https = "0.0.0.0"
  grpc  = "127.0.0.1"
}

ports = {
  dns      = 8600
  # http     = -1
  https    = 8501
  serf_lan = 8301
  serf_wan = 8302
  server   = 8300
  grpc     = -1
}

performance = {
  raft_multiplier  = 1
  leave_drain_time = "5s"
  rpc_hold_timeout = "7s"
}

## Raft
raft_protocol = 3

## Agent
data_dir                   = "${data_dir}"
# log_level                  = "INFO"
log_level                  = "DEBUG"
enable_syslog              = true
syslog_facility            = "local0"
# disable_update_check       = false
# enable_script_checks       = false
# enable_local_script_checks = false

## Encryption and TLS
encrypt                = "${consul_encrypt}"
# ca_file                = "/etc/consul.d/tls/consul-agent-ca.pem"
# cert_file              = "/etc/consul.d/tls/dc1-server-consul-0.pem"
# key_file               = "/etc/consul.d/tls/dc1-server-consul-0-key.pem"
# verify_incoming        = true
# verify_outgoing        = true
# verify_incoming_https  = false
# verify_server_hostname = true

## LAN Join
retry_interval = "30s"
retry_max      = 0
### cloud auto-join
retry_join     = ["provider=azure vm_scale_set=${vm_scale_set} resource_group=${resource_group} tenant_id=${tenant_id} subscription_id=${subscription_id} client_id=${client_id} secret_access_key=${secret_access_key}"]
### known addresses
# retry_join = [$${consul_nodes}]

## Server Settings
server           = true
bootstrap        = false
bootstrap_expect = ${consul_count}
# autopilot        = {}

## WAN Join
# retry_interval_wan = "30s"
# retry_max_wan      = 0

## ACL
# primary_datacenter = "dc1"
# acl = {
#   enabled        = true
#   default_policy = "deny"
#   down_policy    = "extend-cache"
#   token_ttl      = "30s"
#   tokens         = {}
# }

## UI
ui = true